// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AccueilDocumentDataSlicesSlice =
  | SectionSlice
  | InfluencerSlice
  | ServiceSlice
  | BigTextSlice
  | StorySlice;

/**
 * Content for Accueil documents
 */
interface AccueilDocumentData {
  /**
   * Hero field in *Accueil*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero: prismic.ContentRelationshipField;

  /**
   * Slice Zone field in *Accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccueilDocumentDataSlicesSlice> /**
   * Meta Title field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accueil.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accueil.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Accueil document from Prismic
 *
 * - **API ID**: `accueil`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccueilDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AccueilDocumentData>,
    "accueil",
    Lang
  >;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Copyrights field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyrights
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyrights: prismic.KeyTextField;

  /**
   * logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation field in *Footer*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation: prismic.ContentRelationshipField<"navigation">;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeroDocumentDataSlicesSlice = LinkSlice;

/**
 * Content for Hero documents
 */
interface HeroDocumentData {
  /**
   * Title field in *Hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Brands field in *Hero*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.brands
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brands: prismic.ContentRelationshipField<"marquee">;

  /**
   * Slice Zone field in *Hero*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeroDocumentDataSlicesSlice>;
}

/**
 * Hero document from Prismic
 *
 * - **API ID**: `hero`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HeroDocumentData>, "hero", Lang>;

type InfluencerDocumentDataSlicesSlice = SocialNetworkSlice;

/**
 * Content for Influencer documents
 */
interface InfluencerDocumentData {
  /**
   * Name field in *Influencer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: influencer.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * description field in *Influencer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: influencer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Influencer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: influencer.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Influencer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: influencer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InfluencerDocumentDataSlicesSlice>;
}

/**
 * Influencer document from Prismic
 *
 * - **API ID**: `influencer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InfluencerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InfluencerDocumentData>,
    "influencer",
    Lang
  >;

type MarqueeDocumentDataSlicesSlice = BrandSlice;

/**
 * Content for Marquee documents
 */
interface MarqueeDocumentData {
  /**
   * Slice Zone field in *Marquee*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MarqueeDocumentDataSlicesSlice>;
}

/**
 * Marquee document from Prismic
 *
 * - **API ID**: `marquee`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MarqueeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MarqueeDocumentData>,
    "marquee",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = LinkSlice;

type NavigationDocumentDataSlices1Slice = LinkSlice;

type NavigationDocumentDataSlices2Slice = LinkSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice> /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices1[]
   * - **Tab**: Socials
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<NavigationDocumentDataSlices1Slice> /**
   * Location field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.location
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  location: prismic.RichTextField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices2[]
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices2: prismic.SliceZone<NavigationDocumentDataSlices2Slice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Benefit field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.benefit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  benefit: prismic.RichTextField;

  /**
   * Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes =
  | AccueilDocument
  | FooterDocument
  | HeroDocument
  | InfluencerDocument
  | MarqueeDocument
  | NavigationDocument
  | ServiceDocument;

/**
 * Primary content in *BigText → Default → Primary*
 */
export interface BigTextSliceDefaultPrimary {
  /**
   * Description field in *BigText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for BigText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BigText*
 */
type BigTextSliceVariation = BigTextSliceDefault;

/**
 * BigText Shared Slice
 *
 * - **API ID**: `big_text`
 * - **Description**: BigText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigTextSlice = prismic.SharedSlice<
  "big_text",
  BigTextSliceVariation
>;

/**
 * Primary content in *Brand → Default → Primary*
 */
export interface BrandSliceDefaultPrimary {
  /**
   * Image field in *Brand → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Brand Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Brand*
 */
type BrandSliceVariation = BrandSliceDefault;

/**
 * Brand Shared Slice
 *
 * - **API ID**: `brand`
 * - **Description**: Brand
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandSlice = prismic.SharedSlice<"brand", BrandSliceVariation>;

/**
 * Primary content in *Influencer → Default → Primary*
 */
export interface InfluencerSliceDefaultPrimary {
  /**
   * Influencer field in *Influencer → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: influencer.default.primary.influencer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  influencer: prismic.ContentRelationshipField<"influencer">;
}

/**
 * Default variation for Influencer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfluencerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfluencerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Influencer*
 */
type InfluencerSliceVariation = InfluencerSliceDefault;

/**
 * Influencer Shared Slice
 *
 * - **API ID**: `influencer`
 * - **Description**: Influencer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfluencerSlice = prismic.SharedSlice<
  "influencer",
  InfluencerSliceVariation
>;

/**
 * Primary content in *Link → Default → Primary*
 */
export interface LinkSliceDefaultPrimary {
  /**
   * Link field in *Link → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * New Tab field in *Link → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: link.default.primary.new_tab
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  new_tab: prismic.BooleanField;

  /**
   * Label field in *Link → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Link Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Link*
 */
type LinkSliceVariation = LinkSliceDefault;

/**
 * Link Shared Slice
 *
 * - **API ID**: `link`
 * - **Description**: Link
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSlice = prismic.SharedSlice<"link", LinkSliceVariation>;

/**
 * Item in *Section → influencers → Primary → Sections*
 */
export interface SectionSliceDefaultPrimarySectionsItem {
  /**
   * Section field in *Section → influencers → Primary → Sections*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.sections[].section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"influencer">;
}

/**
 * Item in *Section → Story → Primary → Sections*
 */
export interface SectionSliceStoryPrimarySectionsItem {
  /**
   * Description field in *Section → Story → Primary → Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.story.primary.sections[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *Section → Services → Primary → Sections*
 */
export interface SectionSliceServicesPrimarySectionsItem {
  /**
   * Section field in *Section → Services → Primary → Sections*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section.services.primary.sections[].section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"service">;
}

/**
 * Primary content in *Section → influencers → Primary*
 */
export interface SectionSliceDefaultPrimary {
  /**
   * Section id field in *Section → influencers → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_id: prismic.KeyTextField;

  /**
   * Description field in *Section → influencers → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Sections field in *Section → influencers → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section.default.primary.sections[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<
    Simplify<SectionSliceDefaultPrimarySectionsItem>
  >;
}

/**
 * influencers variation for Section Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Section → contact → Primary*
 */
export interface SectionSliceContactPrimary {
  /**
   * Section id field in *Section → contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.contact.primary.section_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_id: prismic.KeyTextField;

  /**
   * Description field in *Section → contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.contact.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * contact variation for Section Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceContact = prismic.SharedSliceVariation<
  "contact",
  Simplify<SectionSliceContactPrimary>,
  never
>;

/**
 * Primary content in *Section → Story → Primary*
 */
export interface SectionSliceStoryPrimary {
  /**
   * Section id field in *Section → Story → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.story.primary.section_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_id: prismic.KeyTextField;

  /**
   * Description field in *Section → Story → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.story.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Sections field in *Section → Story → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section.story.primary.sections[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<Simplify<SectionSliceStoryPrimarySectionsItem>>;
}

/**
 * Story variation for Section Slice
 *
 * - **API ID**: `story`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceStory = prismic.SharedSliceVariation<
  "story",
  Simplify<SectionSliceStoryPrimary>,
  never
>;

/**
 * Primary content in *Section → Services → Primary*
 */
export interface SectionSliceServicesPrimary {
  /**
   * Section id field in *Section → Services → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.services.primary.section_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_id: prismic.KeyTextField;

  /**
   * Description field in *Section → Services → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section.services.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Sections field in *Section → Services → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section.services.primary.sections[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<
    Simplify<SectionSliceServicesPrimarySectionsItem>
  >;
}

/**
 * Services variation for Section Slice
 *
 * - **API ID**: `services`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceServices = prismic.SharedSliceVariation<
  "services",
  Simplify<SectionSliceServicesPrimary>,
  never
>;

/**
 * Slice variation for *Section*
 */
type SectionSliceVariation =
  | SectionSliceDefault
  | SectionSliceContact
  | SectionSliceStory
  | SectionSliceServices;

/**
 * Section Shared Slice
 *
 * - **API ID**: `section`
 * - **Description**: Section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSlice = prismic.SharedSlice<
  "section",
  SectionSliceVariation
>;

/**
 * Primary content in *Service → Default → Primary*
 */
export interface ServiceSliceDefaultPrimary {
  /**
   * Service field in *Service → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service: prismic.ContentRelationshipField<"service">;
}

/**
 * Default variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Service*
 */
type ServiceSliceVariation = ServiceSliceDefault;

/**
 * Service Shared Slice
 *
 * - **API ID**: `service`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSlice = prismic.SharedSlice<
  "service",
  ServiceSliceVariation
>;

/**
 * Primary content in *SocialNetwork → Default → Primary*
 */
export interface SocialNetworkSliceDefaultPrimary {
  /**
   * label field in *SocialNetwork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_network.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *SocialNetwork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_network.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * number field in *SocialNetwork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_network.default.primary.number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;
}

/**
 * Default variation for SocialNetwork Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialNetworkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialNetworkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialNetwork*
 */
type SocialNetworkSliceVariation = SocialNetworkSliceDefault;

/**
 * SocialNetwork Shared Slice
 *
 * - **API ID**: `social_network`
 * - **Description**: SocialNetwork
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialNetworkSlice = prismic.SharedSlice<
  "social_network",
  SocialNetworkSliceVariation
>;

/**
 * Primary content in *Story → Default → Primary*
 */
export interface StorySliceDefaultPrimary {
  /**
   * Description field in *Story → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Story Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Story*
 */
type StorySliceVariation = StorySliceDefault;

/**
 * Story Shared Slice
 *
 * - **API ID**: `story`
 * - **Description**: Story
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySlice = prismic.SharedSlice<"story", StorySliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AccueilDocument,
      AccueilDocumentData,
      AccueilDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HeroDocument,
      HeroDocumentData,
      HeroDocumentDataSlicesSlice,
      InfluencerDocument,
      InfluencerDocumentData,
      InfluencerDocumentDataSlicesSlice,
      MarqueeDocument,
      MarqueeDocumentData,
      MarqueeDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      NavigationDocumentDataSlices1Slice,
      NavigationDocumentDataSlices2Slice,
      ServiceDocument,
      ServiceDocumentData,
      AllDocumentTypes,
      BigTextSlice,
      BigTextSliceDefaultPrimary,
      BigTextSliceVariation,
      BigTextSliceDefault,
      BrandSlice,
      BrandSliceDefaultPrimary,
      BrandSliceVariation,
      BrandSliceDefault,
      InfluencerSlice,
      InfluencerSliceDefaultPrimary,
      InfluencerSliceVariation,
      InfluencerSliceDefault,
      LinkSlice,
      LinkSliceDefaultPrimary,
      LinkSliceVariation,
      LinkSliceDefault,
      SectionSlice,
      SectionSliceDefaultPrimarySectionsItem,
      SectionSliceDefaultPrimary,
      SectionSliceContactPrimary,
      SectionSliceStoryPrimarySectionsItem,
      SectionSliceStoryPrimary,
      SectionSliceServicesPrimarySectionsItem,
      SectionSliceServicesPrimary,
      SectionSliceVariation,
      SectionSliceDefault,
      SectionSliceContact,
      SectionSliceStory,
      SectionSliceServices,
      ServiceSlice,
      ServiceSliceDefaultPrimary,
      ServiceSliceVariation,
      ServiceSliceDefault,
      SocialNetworkSlice,
      SocialNetworkSliceDefaultPrimary,
      SocialNetworkSliceVariation,
      SocialNetworkSliceDefault,
      StorySlice,
      StorySliceDefaultPrimary,
      StorySliceVariation,
      StorySliceDefault,
    };
  }
}
