// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  big_text: dynamic(() => import("./BigText")),
  brand: dynamic(() => import("./Brand")),
  influencer: dynamic(() => import("./Influencer")),
  link: dynamic(() => import("./Link")),
  section: dynamic(() => import("./Section")),
  service: dynamic(() => import("./Service")),
  social_network: dynamic(() => import("./SocialNetwork")),
  story: dynamic(() => import("./Story")),
};
